<?php $this->headTitle('Home'); ?>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-4" id="header">
            Watch TV shows & movies anytime, anywhere.
            <p>Plans from EUR7.99 a month</p>

            <button onclick="window.location.href='/select-plan'" type="button" class="btn btn-danger btn-lg">Start Your Free Month</button>
        </div>
    </div>
</div>