<?php $this->headTitle('Premium Content'); ?>
<div class="row" style="margin-top: 60px;">
    <div class="col-md-4">
        <div style="font-size: 28px; text-align: center; padding-bottom: 10px;">ORIGINAL</div>
        <img src="/images/arrow-logo.png" style="width: 400px; padding-bottom: 20px;"/>
        <strong>Laurel brings a civil suit against millionaire Martin Somers</strong><br/><br/>
        Who is also one of Oliver's targets, for taking part in drug trades with the Chinese Triad that ultimately led to the death of a young woman's father.
        <br/><br/>
        <button type="button" class="btn btn-danger">Watch trailer</button>
        <button type="button" class="btn btn-danger">Watch whole episode</button>
    </div>
    <div class="col-md-offset-1 col-md-7">
        <div class="aspect-ratio">
            <iframe width="100%" height="100%" src="https://www.youtube.com/embed/uaDb-2XHK5U?rel=0&controls=0&showinfo=0&autoplay=1" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>