<?php $this->headTitle('Premium Content'); ?>
<div class="row">
    <div class="col-md-4" style="font-size: 28px; text-align: center; padding: 60px 0 10px;">
        ORIGINAL
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <img src="/images/arrow-logo.png" style="width: 400px; padding-bottom: 20px;"/>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <strong>Laurel brings a civil suit against millionaire Martin Somers</strong><br/><br/>
        Who is also one of Oliver's targets, for taking part in drug trades with the Chinese Triad that ultimately led to the death of a young woman's father.
        <br/><br/>
        <button type="button" class="btn btn-danger">Watch trailer</button>
        <button type="button" class="btn btn-danger">Watch whole episode</button>
    </div>
</div>