<?php $this->headTitle('Premium Content'); ?>
<div class="row" style="margin-top: 60px;">
    <div class="col-md-4">
        <strong>
            Icing icing tart. Candy pudding liquorice muffin. Cotton candy tootsie roll biscuit lemon drops. Chocolate bar sugar plum caramels. Sweet candy canes dragée soufflé cheesecake cookie gingerbread cotton candy topping. Liquorice candy cake candy canes. Chupa chups pudding topping oat cake cake tootsie roll icing. Brownie fruitcake topping soufflé lollipop. Croissant bonbon cotton candy pastry pastry bonbon lemon drops. Sesame snaps icing tiramisu gummi bears bear claw bear claw macaroon cheesecake candy. Chupa chups croissant biscuit brownie. Toffee lollipop marshmallow chocolate bar. Macaroon marshmallow gummi bears bonbon gummi bears. Donut jujubes bonbon pastry sweet.
            <br/><br/>
            <button type="button" class="btn btn-danger tooltip-trigger" data-placement="bottom">Watch trailer</button>
            <button type="button" class="btn btn-danger tooltip-trigger" data-placement="bottom">Watch whole episode</button>
    </div>
    <div class="col-md-offset-1 col-md-7">
        <div class="aspect-ratio">
            <iframe style="border:none" width="100%" height="100%" src="http://content.uplynk.com/player/4ZliT75VnM2cok7CCwOdeNea.html"></iframe>
        </div>
    </div>
</div>