<div class="row">
    <div class="col-md-offset-3 col-md-6" id="select-plan">
        <h3>Choose the plan that's right for you:</h3>
        &nbsp;&nbsp;&nbsp;&nbsp;Sign up now, and get you free month!
        <ul>
            <li>
                <div>
                    <strong>Week Pass</strong><br/>
                    Access for 7 days
                </div>
                <a href="/authenticate?offerId=P852360119_NL" class="btn btn-danger">Select</a>
                <p class="price">$5.99</p>
            </li>
            <li>
                <div>
                    <strong>Monthly Subscription</strong><br/>
                    Access for whole month (<strong>FREE</strong> month included!)
                </div>
                <a href="/authenticate?offerId=S359644062_NL" class="btn btn-danger">Select</a>
                <p class="price">$7.99</p>
            </li>
            <li>
                <div>
                    <strong>3-Month Subscription</strong><br/>
                    Access for 3 months (<strong>FREE</strong> month included!)
                </div>
                <a href="/authenticate?offerId=S661682819_NL" class="btn btn-danger">Select</a>
                <p class="price">$19.99</p>
            </li>
            <li>
                <div>
                    <strong>Annual Subscription</strong><br/>
                    Access for whole year! (<strong>FREE</strong> month included!)
                </div>
                <a href="/authenticate?offerId=S164745395_NL" class="btn btn-danger">Select</a>
                <p class="price">$79.99</p>
            </li>
        </ul>
    </div>
</div>