<div class="row" xmlns="http://www.w3.org/1999/html">
    <div class="col-md-offset-3 col-md-6" style="padding-top: 70px;">
        <?php if ($this->mode == 'profile'): ?>
            <iframe src="https://selfcare.cleeng.com/us/mybrandtv-live?order=profile" style="width: 100%; height: 800px; border: 0;"></iframe>
        <?php else: ?>
            <iframe src="https://selfcare.cleeng.com/us/mybrandtv-live?order=subscriptions,payment,transactions" style="width: 100%; height: 800px; border: 0;"></iframe>
        <?php endif; ?>
    </div>
</div>