<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>SVOD Platform - Authentication - Cleeng demo</title>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink()
        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
        ->prependStylesheet('css/main.css?1')
    ?>
</head>
<body id="authenticate">
<!-- Navbar -->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">MyBrand.tv</a>
        </div>
    </div>
</nav>

<!-- Begin page content -->
<div class="container-fluid">
    <?php echo $this->content ?>
</div>
<script>
    function cleengCallbackHandler(result) {
        if (result.accessGranted == true) {
            window.location.href = '/premium-content';
        }
    }
</script>
<?php echo $this->headScript()
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js')
    ->prependFile('http://cdn.cleeng.com/js-api/3.0/api.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');

echo $this->inlineScript();
?>
</body>
</html>
