<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>SVOD Platform - Cleeng demo</title>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink()
        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
        ->prependStylesheet('css/main.css')
    ?>
</head>
<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">MyBrand.tv</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
                <li>
                    <button class="btn btn-danger"
                         data-cleeng-trigger
                         data-action="authentication"
                         data-display-type="overlay"
                         data-publisher-id="120680532"
                         data-completed-callback="cleengCallbackHandler(result)">Sign in</div>
                </li>
            </ul>
        </div>
        <!--/.nav-collapse -->
    </div>
</nav>

<!-- Begin page content -->
<div class="container-fluid">
    <?php echo $this->content ?>
</div>

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-offset-1 col-md-3">
                <img src="https://assets.nflxext.com/ffe/siteui/acquisition/common/bullets/online_streaming_2.png" />
                <p>
                    Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia.
                </p>
            </div>
            <div class="col-md-4">
                <img src="https://assets.nflxext.com/ffe/siteui/acquisition/common/bullets/watch_on_devices_2.png" />
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                </p>
            </div>
            <div class="col-md-3">
                <img src="https://assets.nflxext.com/ffe/siteui/acquisition/common/bullets/cancel_anytime_2.png" />
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
                </p>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->headScript()
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('http://cdn.cleeng.com/js-api/3.0/api.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');

echo $this->inlineScript();
?>
<script>
    $.backstretch("/images/homepage_bg.jpg");
    function cleengCallbackHandler(result) {
        if (result.authorizationSuccessful) {
            CleengApi.getAccessStatus('A764667811_NL', function (accessStatus) {
                if (accessStatus.accessGranted) {
                    window.location.href = '/premium-content';
                } else {
                    wi;
                }
            });
        }
    };
</script>
</body>
</html>
