<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>SVOD Platform - Cleeng demo</title>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink()
        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css')
        ->prependStylesheet('css/main.css')
    ?>
</head>
<body>
<?php if($this->showHomePageNotification()): ?>
    <div id="homepage-notification">
        <span>This is a Cleeng SVOD demo website. <a href="https://cleeng.com/contact">Contact us</a>, or <a href="https://cleeng.com/open">develop your own</a>.</span>
    </div>
<?php endif; ?>
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">MyBrand.tv</a>
        <div class="btn-group">
            <?php if($this->getCleengCustomer()): ?>
                <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Hi <?php echo $this->getCleengCustomer()->displayName; ?> <span class="caret"></span>
                </button>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="/select-plan">Start your FREE month</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#" id="logout">Logout</a></li>
                </ul>
            <?php else: ?>
                <button class="btn btn-danger"
                        data-cleeng-trigger
                        data-action="authentication"
                        data-locale="en_US"
                        data-display-type="overlay"
                        data-publisher-id="120680532"
                        data-completed-callback="cleengCallbackHandler(result)">Sign in</button>
            <?php endif; ?>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <?php echo $this->content ?>
</div>

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-offset-1 col-sm-3">
                <img src="/images/onlinestreaming.png" />
                <p>
                    Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia.
                </p>
            </div>
            <div class="col-sm-4">
                <img src="/images/watchondevices.png" />
                <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                </p>
            </div>
            <div class="col-sm-3">
                <img src="/images/cancelanytime.png" />
                <p>
                    Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa.
                </p>
            </div>
        </div>
    </div>
</footer>
<?php echo $this->headScript()
    ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/jquery-backstretch/2.0.4/jquery.backstretch.min.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js')
    ->prependFile('http://cdn.cleeng.com/js-api/3.0/api.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');

echo $this->inlineScript();
?>
<div id="cleeng-tip-holder">
    <div id="cleeng-tip">
        <span class="glyphicon glyphicon-remove"></span>
        <h4>Hi there!</h4>
        Because it is only a demo and we don't want you to pay for the access to fake movies, here you can find the 100% discount code. Use it during payment process:
        <h3 id="subscriptionDiscount">discountForYou</h3>
        <h3 id="passDiscount">freeForYou</h3>
    </div>
</div>
<script>
    window.loggedIn = <?php echo json_encode((bool)$this->getCleengCustomer()); ?>;

    $.backstretch("/images/homepage_bg.jpg");
    function cleengCallbackHandler(result) {
        if (result.authorizationSuccessful) {
            CleengApi.getAccessStatus('A764667811_NL', function (accessStatus) {
                if (accessStatus.accessGranted) {
                    window.location.href = '/premium-content';
                } else {
                    window.location.href = '/';
                }
            });
        }
    }
    $('#logout').click(function() {
        CleengApi.logout(function(result) {
            if (result.success) {
                location.reload();
            }
        });
    });
    $('#justAdemo a').click(function() {
        $('#cleeng-tip').addClass('show');
        $('#cleeng-tip h3').hide();
        if ($(this).hasClass('pass')) {
            $('#passDiscount').show();
        } else {
            $('#subscriptionDiscount').show();
        }
        $('#justAdemo').modal('hide')
    });
    $('#cleeng-tip span').click(function() {
        $('#cleeng-tip').removeClass('show');
    });
    CleengApi.autologin(function(result) {
        if (result.success && !window.loggedIn) {
            location.reload();
        }
    });
</script>
</body>
</html>
