<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">
    <title>SVOD Platform - Cleeng demo</title>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headLink()
        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')
        ->prependStylesheet('css/main.css?2')
    ?>
</head>
<body id="premium-content">
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/">MyBrand.tv</a>
        </div>
        <div id="navbar" class="navbar-right">
            <ul class="nav navbar-nav">
                <li>
                    <div class="btn-group">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hi <?php echo $this->getCleengCustomer()->displayName; ?> <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a data-toggle="modal" data-target="#profile">Profile</a></li>
                            <li><a data-toggle="modal" data-target="#subscription">Subscription</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#" id="logout">Logout</a></li>
                        </ul>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container-fluid">
    <?php echo $this->content ?>
</div>

<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <img src="/images/thumb9.jpg" class="tooltip-trigger"/>
            <img src="/images/thumb8.jpg" class="tooltip-trigger"/>
            <img src="/images/thumb7.jpg" class="tooltip-trigger"/>
            <img src="/images/thumb2.png" class="tooltip-trigger"/>
            <img src="/images/thumb5.png" class="tooltip-trigger"/>
            <img src="/images/thumb6.png" class="tooltip-trigger"/>
            <img src="/images/thumb1.png" class="tooltip-trigger"/>
        </div>
        </div>
    </div>
</footer>
<div class="modal fade" id="profile" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <iframe src="https://myaccount.cleeng.com/us/mybrandtv-live?order=profile" style="width: 100%; height: 600px; border: 0;"></iframe>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="subscription" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
                <iframe src="https://myaccount.cleeng.com/us/mybrandtv-live?order=subscriptions,payment,transactions" style="width: 100%; height: 600px; border: 0;"></iframe>
            </div>
        </div>
    </div>
</div>
<?php echo $this->headScript()
    ->prependFile('http://cdn.cleeng.com/js-api/3.0/api.js')
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-2.1.4.min.js');

?>
<script>
    $('#logout').click(function() {
        CleengApi.logout(function(result) {
            if (result.success) {
                location.reload();
            }
        });
    });

    $(function () {
        $('.tooltip-trigger').tooltip({
            'trigger': 'click',
            'title': "This is a demo.",
        })
    });

    $(document).on('shown.bs.tooltip', function (e) {
        setTimeout(function () {
            $(e.target).tooltip('hide');
        }, 1000);
    });
</script>
<div id="darker"></div>
</body>
</html>
